spring.application.name=spring-sunshine
server.port=8081

# Google AI Configuration
spring.ai.google.genai.api-key=
spring.ai.google.genai.project-id=
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
